### ISSUE TITLE
Does not work on netbox-3.1.10

### ISSUE THREAD

**Issue by quiknick** [netdevopsbr/netbox-proxbox#39]
netbox-proxbox 0.0.3 does not work on netbox 3.1.10. See the following stack track from python3 manage.py migrate

python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/opt/netbox/netbox/extras/plugins/__init__.py", line 61, in ready
    template_extensions = import_object(f"{self.__module__}.{self.template_extensions}")
  File "/opt/netbox/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
AttributeError: 'zipimporter' object has no attribute 'exec_module'

**Comment by quiknick** [comment]
<class 'django.template.exceptions.TemplateDoesNotExist'>

base.html

Python version: 3.8.10
NetBox version: 3.1.10

**Comment by quiknick** [comment]
# pip3 list
Package                       Version    Editable project location
----------------------------- ---------- --------------------------------------------------------------------------------
aniso8601                     7.0.0
asgiref                       3.5.0
async-timeout                 4.0.2
attrs                         21.4.0
backports.zoneinfo            0.2.1
bcrypt                        3.2.0
CacheControl                  0.12.10
cachy                         0.3.0
certifi                       2021.10.8
cffi                          1.15.0
charset-normalizer            2.0.12
ciscoconfparse                1.6.40
cleo                          1.0.0a4
click                         8.1.1
coreapi                       2.3.3
coreschema                    0.0.4
crashtest                     0.3.1
cryptography                  36.0.2
cycler                        0.11.0
defusedxml                    0.7.1
Deprecated                    1.2.13
distlib                       0.3.4
Django                        3.2.12
django-cors-headers           3.11.0
django-debug-toolbar          3.2.4
django-filter                 21.1
django-graphiql-debug-toolbar 0.2.0
django-js-asset               2.0.0
django-mptt                   0.13.4
django-pglocks                1.0.4
django-prometheus             2.2.0
django-redis                  5.2.0
django-rq                     2.5.1
django-tables2                2.4.1
django-taggit                 2.1.0
django-timezone-field         5.0
djangorestframework           3.13.1
dnspython                     2.2.1
drf-yasg                      1.20.0
dulwich                       0.20.35
entrypoints                   0.3
filelock                      3.6.0
fonttools                     4.31.2
future                        0.18.2
ghp-import                    2.0.2
gitdb                         4.0.9
GitPython                     3.1.27
graphene                      2.1.9
graphene-django               2.15.0
graphql-core                  2.3.2
graphql-relay                 2.0.1
gunicorn                      20.1.0
html5lib                      1.1
idna                          3.3
importlib                     1.0.4
importlib-metadata            4.11.3
inflection                    0.5.1
invoke                        1.7.0
itypes                        1.2.0
jeepney                       0.7.1
Jinja2                        3.0.3
jsonschema                    3.2.0
junos-eznc                    2.6.3
keyring                       23.5.0
kiwisolver                    1.4.2
lizard                        1.17.9
lockfile                      0.12.2
loguru                        0.6.0
lxml                          4.8.0
Markdown                      3.3.6
markdown-include              0.6.0
MarkupSafe                    2.1.1
matplotlib                    3.5.1
mergedeep                     1.3.4
mkdocs                        1.3.0
mkdocs-material               8.2.7
mkdocs-material-extensions    1.0.3
msgpack                       1.0.3
napalm                        3.4.0
ncclient                      0.6.9
netaddr                       0.8.0
netbox-config-backup          1.0.2
netbox-dns                    0.9.1
netbox-ipcalculator           1.1
netbox-plugin-extensions      1.1.1
netbox-proxbox                0.0.3.dev3 /opt/netbox/venv/lib/python3.8/site-packages/netbox_proxbox-0.0.3.dev3-py3.8.egg
netmiko                       3.4.0
nextbox-ui-plugin             0.9.2
np-autodiscovery              1.0.2
ntc-netbox-plugin-onboarding  2.2.0
ntc-templates                 3.0.0
numpy                         1.22.3
oauthlib                      3.2.0
packaging                     20.9
paramiko                      2.10.3
passlib                       1.7.4
pexpect                       4.8.0
Pillow                        9.0.1
pip                           22.0.4
pkg_resources                 0.0.0
pkginfo                       1.8.2
platformdirs                  2.5.1
poetry                        1.2.0b1
poetry-core                   1.1.0a7
prometheus-client             0.13.1
promise                       2.3
proxmoxer                     1.3.0
psycopg2-binary               2.9.3
ptyprocess                    0.7.0
pycparser                     2.21
PyDriller                     2.1
pyeapi                        0.8.4
Pygments                      2.11.2
PyJWT                         2.3.0
pylev                         1.4.0
pymdown-extensions            9.3
PyNaCl                        1.5.0
pynetbox                      6.6.1
pyparsing                     3.0.7
pyrsistent                    0.18.1
pyserial                      3.5
python-dateutil               2.8.2
python3-openid                3.2.0
pytz                          2022.1
PyYAML                        6.0
pyyaml_env_tag                0.1
redis                         4.2.0
requests                      2.27.1
requests-oauthlib             1.3.1
requests-toolbelt             0.9.1
rq                            1.10.1
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
Rx                            1.6.1
scp                           0.14.4
SecretStorage                 3.3.1
setuptools                    44.0.0
shellingham                   1.4.0
singledispatch                3.7.0
six                           1.16.0
smmap                         5.0.0
social-auth-app-django        5.0.0
social-auth-core              4.2.0
sqlparse                      0.4.2
svgwrite                      1.4.2
swagger-spec-validator        2.7.4
tablib                        3.2.0
tenacity                      8.0.1
text-unidecode                1.3
textfsm                       1.1.2
toml                          0.10.2
tomlkit                       0.10.1
transitions                   0.8.11
types-pytz                    2021.3.6
typing_extensions             4.1.1
tzdata                        2021.5
uritemplate                   4.1.1
urllib3                       1.26.9
uuid                          1.30
virtualenv                    20.14.0
watchdog                      2.1.7
webencodings                  0.5.1
wheel                         0.37.1
wrapt                         1.14.0
yamlordereddictloader         0.4.0
zipp                          3.7.0

**Comment by quiknick** [comment]
0.0.3 does not work in netbox 3.1.6 either.

**Comment by emersonfelipesp** [comment]
Proxbox will now support only Netbox v3.2.0 or higher, as a lot of plugin related features was created or changed.
